name:                ext-effects
version:             0.1.0.0
github:              "githubuser/ext-effects"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ext-effects#readme>

dependencies:
- base >= 4.7 && < 5
- extensible-effects >= 1.11
- mtl >= 2.2.1
- containers >= 0.5.7.1
- resourcet >= 1.1.9
- lens >= 4

library:
  source-dirs: src

executables:
  ext-effects-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ext-effects

tests:
  ext-effects-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ext-effects
